version: "3.4"

services:
  couchdb:
    container_name: leihlokal-couchdb
    image: couchdb:3
    restart: unless-stopped
    ports:
      - 5984:5984
      - 6984:6984
    volumes:
      - ./CouchDb/couchdb_config:/opt/couchdb/etc/local.d
      - ./CouchDb/couchdb_ssl:/opt/couchdb/ssl

  testdata_generator:
    build:
      context: ./TestDataGenerator
      dockerfile: Dockerfile
    container_name: testdata_generator
    restart: on-failure
    depends_on:
      - "couchdb"
