module.exports = {
  id: "14",
  lastname: "Daville",
  firstname: "Zea",
  street: "Mockingbird",
  house_number: "8",
  postal_code: "46222",
  city: "Budapest",
  registration_date: "18.09.2019",
  renewed_on: "-",
  remark: "",
  email: "zdaville8l@macromedia.com",
  telephone_number: "1706 0830 31",
  subsribed_to_newsletter: false,
  heard: "gesehen, vorbeigelaufen",
};
