version: "3.4"

x-common-variables: &common-variables
  COUCHDB_USER: "user"
  COUCHDB_PASSWORD: "password"
  DEV: "true"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 12
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    ports:
      - 35729:35729
      - 5000:5000

    environment:
      <<: *common-variables
      COUCHDB_HOST: 127.0.0.1:5984

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  couchdb:
    image: couchdb:3.1.0
    restart: unless-stopped
    ports:
      - 5984:5984
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./couchdb:/opt/couchdb/etc/local.d

volumes:
  couchdb-data:
