export default [
  {
    _id: "1",
    lastname: "Cohen",
    firstname: "Velasquez",
    registration_date: 1538949600000,
    renewed_on: 0,
    remark: "",
    subscribed_to_newsletter: false,
    email: "rmcfarla@outlook.com",
    street: "Blumentorstrasse",
    house_number: 8,
    postal_code: "76135",
    city: "Karlsruhe",
    telephone_number: "01761881433",
    heard: "",
  },
  {
    _id: "2",
    lastname: "Nicholas",
    firstname: "Collins",
    registration_date: 1539295200000,
    renewed_on: 1570838400000,
    remark: "",
    subscribed_to_newsletter: true,
    email: "hachi@gmail.com",
    street: "Klauprechtstraße",
    house_number: 56,
    postal_code: "76131",
    city: "Karlsruhe",
    telephone_number: "01768701629",
    heard: "",
  },
  {
    _id: "3",
    lastname: "Albert",
    firstname: "Morris",
    registration_date: 0,
    renewed_on: 0,
    remark: "",
    subscribed_to_newsletter: false,
    email: "andersbr@att.net",
    street: "Berckmüllerstraße",
    house_number: 10,
    postal_code: "76131",
    city: "Karlsruhe",
    telephone_number: "01761411340",
    heard: "",
  },
  {
    _id: "4",
    lastname: "Uriel",
    firstname: "Gibson",
    registration_date: 1546038000000,
    renewed_on: 1577577600000,
    remark: "",
    subscribed_to_newsletter: false,
    email: "mcraigw@yahoo.com",
    street: "Werthmannstraße",
    house_number: 58,
    postal_code: "76137",
    city: "Karlsruhe",
    telephone_number: "01761881433",
    heard: "gesehen, vorbeigelaufen",
  },
  {
    _id: "5",
    lastname: "Viviana",
    firstname: "Peters",
    registration_date: 1546214400000,
    renewed_on: 0,
    remark: "",
    subscribed_to_newsletter: false,
    email: "kannan@sbcglobal.net",
    street: "Gerwigstraße",
    house_number: 97,
    postal_code: "75417",
    city: "Karlsruhe",
    telephone_number: "01764337303",
    heard: "",
  },
  {
    _id: "6",
    lastname: "Bailee",
    firstname: "Jennings",
    registration_date: 1546470000000,
    renewed_on: 0,
    remark: "",
    subscribed_to_newsletter: true,
    email: "augusto@yahoo.com",
    street: "Am Sandberg",
    house_number: 6,
    postal_code: "76131",
    city: "Karlsruhe",
    telephone_number: "01765338748",
    heard: "gesehen, vorbeigelaufen",
  },
  {
    _id: "7",
    lastname: "Kadyn",
    firstname: "Hernandez",
    registration_date: 1546560000000,
    renewed_on: 0,
    remark: "",
    subscribed_to_newsletter: true,
    email: "thaljef@hotmail.com",
    street: "Schückstrasse",
    house_number: 88,
    postal_code: "76131",
    city: "Karlsruhe",
    telephone_number: "01769851841",
    heard: "Internet",
  },
  {
    _id: "8",
    lastname: "Dominic",
    firstname: "Wise",
    registration_date: 1546646400000,
    renewed_on: 0,
    remark: "",
    subscribed_to_newsletter: false,
    email: "brainless@me.com",
    street: "Striederstraße",
    house_number: 67,
    postal_code: "76744",
    city: "Maximiliansau",
    telephone_number: "01762916259",
    heard: "",
  },
  {
    _id: "9",
    lastname: "Lizeth",
    firstname: "Krause",
    registration_date: 1546732800000,
    renewed_on: 0,
    remark: "",
    subscribed_to_newsletter: false,
    email: "webdragon@optonline.net",
    street: "Glümerstraße",
    house_number: 11,
    postal_code: "76139",
    city: "Karlsruhe",
    telephone_number: "01769252281",
    heard: "",
  },
  {
    _id: "10",
    lastname: "Ada",
    firstname: "Mcmillan",
    registration_date: 1546819200000,
    renewed_on: 0,
    remark: "",
    subscribed_to_newsletter: false,
    email: "mhassel@optonline.net",
    street: "Dunantstraße",
    house_number: 93,
    postal_code: "76131",
    city: "Karlsruhe",
    telephone_number: "01761569947",
    heard: "",
  },
];
