import COLORS from "../../../src/components/Input/ColorDefs";

export default [
  {
    _id: "0001",
    item_name: "Dekupiersäge",
    brand: "King Craft",
    itype: "KFZ-400RV",
    category: "Heimwerker",
    deposit: 55,
    parts: "1",
    added: 1579255200000,
    description: "",
    status: "instock",
    wc_url:
      "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/heimwerker/dekupiersaege-3/",
    wc_id: 3302,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/005.jpg",
    highlight: COLORS.HIGHLIGHT_BLUE,
  },
  {
    _id: "0002",
    item_name: "Raclette",
    brand: "Tefal",
    itype: "Grill Deluxe",
    category: "Küche",
    deposit: 15,
    parts: "12",
    added: 1580346000000,
    description: "8 Pfännchen ohne Schieber mit Crèpezubehör, mit Grillfunktion",
    status: "instock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/kueche/raclette-8/",
    wc_id: 3328,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/002.jpg",
  },
  {
    _id: "0003",
    item_name: "Schinkenmaker",
    brand: "gs-mm Germany",
    itype: "KASCHKA",
    category: "",
    deposit: 5,
    parts: "7",
    added: 1580342400000,
    description: "Schinkenmacher zur Herstellung von Bioaufschnitt, aus Edelstahl",
    status: "deleted",
  },
  {
    _id: "0004",
    item_name: "Mini- Ofen",
    brand: "Tefal",
    itype: "KASCHKA",
    category: "",
    deposit: 15,
    parts: "1",
    added: 1580342400000,
    description: "",
    status: "deleted",
  },
  {
    _id: "0005",
    item_name: "Eishörnchen- Waffeleisen",
    brand: "Tchibo",
    itype: "239725",
    category: "Küche",
    deposit: 15,
    parts: "1",
    added: 1580349600000,
    description: "",
    status: "outofstock",
    wc_url:
      "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/kueche/eishoernchen-waffeleisen/",
    wc_id: 3346,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/005.jpg",
  },
  {
    _id: "0006",
    item_name: "Photoscanner",
    brand: "Ion",
    itype: "Photo slide and Film scanner",
    category: "Freizeit",
    deposit: 15,
    parts: "8",
    added: 1580342400000,
    description: "mit zwei 2GB Speicherkarten",
    status: "instock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/freizeit/photoscanner/",
    wc_id: 3348,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/006.jpg",
  },
  {
    _id: "0007",
    item_name: "Akku Bohrschrauber",
    brand: "Bonus, Max Bahr",
    itype: "909003 2008",
    category: "Heimwerker",
    deposit: 15,
    parts: "8",
    added: 1580342400000,
    description: "ABS 18VE (18 V) mit 2 Maschinen 3 Akkus 2 Ladestationen und 1 Ladekabel",
    status: "outofstock",
    synonyms: "Bohrer",
    wc_url:
      "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/heimwerker/akku-bohrschrauber/",
    wc_id: 3349,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/007.jpg",
  },
  {
    _id: "0008",
    item_name: "Nähmaschine",
    brand: "Medion",
    itype: "overlook MD 16600",
    category: "Haushalt",
    deposit: 55,
    parts: "1",
    added: 1580342400000,
    description: "Nähen, Schneidern, Versäubern (1300 Stiche pro Minute)/nur 3 Aufstecker",
    status: "instock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/haushalt/naehmaschine-2/",
    wc_id: 3350,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/008.jpg",
  },
  {
    _id: "0009",
    item_name: "Joghurt-Automat",
    brand: "gourmetmaxx",
    itype: "XJ -10101",
    category: "Küche",
    deposit: 15,
    parts: "8",
    added: 1580342400000,
    description: "7Gläser inkl. Deckel",
    status: "instock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/kueche/einmachglaeser/",
    wc_id: 3351,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/009.jpg",
  },
  {
    _id: "0010",
    item_name: "nicht neu vergeben jetzt 217",
    brand: "",
    itype: "",
    category: "",
    deposit: 0,
    parts: "",
    added: 0,
    description: "",
    status: "deleted",
  },
  {
    _id: "0011",
    item_name: "el. Universal Pfanne",
    brand: "elta",
    itype: "PP 110N",
    category: "Küche",
    deposit: 15,
    parts: "3",
    added: 1581292800000,
    description: "Backen- Grillen- kochen- Dünsten und Warmhalten",
    status: "instock",
    wc_url:
      "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/kueche/e-universal-pfanne/",
    wc_id: 3406,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/02/11.jpg",
  },
  {
    _id: "0012",
    item_name: "Raclette",
    brand: "TCM",
    itype: "64698",
    category: "Küche",
    deposit: 15,
    parts: "1188",
    added: 1581292800000,
    description: "mit Stufenloser Temperatur- Einstellung, 8 Pfännchen inkl. Schaber",
    status: "instock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/kueche/raclette-9/",
    wc_id: 3420,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/02/12.jpg",
  },
  {
    _id: "0013",
    item_name: "Waffeleisen",
    brand: "Rowenta",
    itype: "KG-85 A86",
    category: "Küche",
    deposit: 15,
    parts: "1",
    added: 1581292800000,
    description: "",
    status: "onbackorder",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/kueche/waffeleisen-6/",
    wc_id: 3421,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/02/13.jpg",
  },
  {
    _id: "0014",
    item_name: "Weihnachtskerzen",
    brand: "Weihnachtskerzen",
    itype: "KASCHKA",
    category: "Haushalt",
    deposit: 5,
    parts: "1",
    added: 1581292800000,
    description:
      "20 teilig LED, mit Saugnäpfen,kabellos →  jede einzelne braucht Batterie +Fernbedienug (nicht alle funktionieren)",
    status: "deleted",
  },
  {
    _id: "0015",
    item_name: "Stichsäge",
    brand: "TOP Craft",
    itype: "TPS 550E",
    category: "Heimwerker",
    deposit: 15,
    parts: "2",
    added: 1581292800000,
    description: "mit Auffangbeutel von Bosch",
    status: "outofstock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/heimwerker/stichsaege-6/",
    wc_id: 3423,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/02/15.jpg",
  },
];
