export default [
  {
    _id: "0001",
    item_name: "Dekupiersäge",
    brand: "King Craft",
    itype: "KFZ-400RV",
    category: "Heimwerker",
    deposit: 55,
    parts: "1",
    manual: "in Schriftform vorhanden",
    package: "originalKarton",
    added: 1579255200000,
    properties: "",
    status_on_website: "instock",
    wc_url:
      "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/heimwerker/dekupiersaege-3/",
    wc_id: 3302,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/3106.jpg",
  },
  {
    _id: "0002",
    item_name: "Raclette",
    brand: "Tefal",
    itype: "Grill Deluxe",
    category: "Küche",
    deposit: 15,
    parts: "12",
    manual: "in Schriftform vorhanden",
    package: "OriginalKarton",
    added: 1580346000000,
    properties: "8 Pfännchen ohne Schieber mit Crèpezubehör, mit Grillfunktion",
    status_on_website: "instock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/kueche/raclette-8/",
    wc_id: 3328,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/002.jpg",
  },
  {
    _id: "0003",
    item_name: "Schinkenmaker",
    brand: "gs-mm Germany",
    itype: "KASCHKA",
    category: "",
    deposit: 5,
    parts: "7",
    manual: "in Schriftform vorhanden",
    package: "originalKarton",
    added: 1580342400000,
    properties: "Schinkenmacher zur Herstellung von Bioaufschnitt, aus Edelstahl",
    status_on_website: "deleted",
  },
  {
    _id: "0004",
    item_name: "Mini- Ofen",
    brand: "Tefal",
    itype: "KASCHKA",
    category: "",
    deposit: 15,
    parts: "1",
    manual: "",
    package: "",
    added: 1580342400000,
    properties: "",
    status_on_website: "deleted",
  },
  {
    _id: "0005",
    item_name: "Eishörnchen- Waffeleisen",
    brand: "Tchibo",
    itype: "239725",
    category: "Küche",
    deposit: 15,
    parts: "1",
    manual: "in Schriftform vorhanden",
    package: "",
    added: 1580349600000,
    properties: "",
    status_on_website: "outofstock",
    wc_url:
      "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/kueche/eishoernchen-waffeleisen/",
    wc_id: 3346,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/005.jpg",
  },
  {
    _id: "0006",
    item_name: "Photoscanner",
    brand: "Ion",
    itype: "Photo slide and Film scanner",
    category: "Freizeit",
    deposit: 15,
    parts: "8",
    manual: "in Schriftform vorhanden",
    package: "originalKarton",
    added: 1580342400000,
    properties: "mit zwei 2GB Speicherkarten",
    status_on_website: "instock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/freizeit/photoscanner/",
    wc_id: 3348,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/006.jpg",
  },
  {
    _id: "0007",
    item_name: "Akku Bohrschrauber",
    brand: "Bonus, Max Bahr",
    itype: "909003 2008",
    category: "Heimwerker",
    deposit: 15,
    parts: "8",
    manual: "",
    package: "",
    added: 1580342400000,
    properties: "ABS 18VE (18 V) mit 2 Maschinen 3 Akkus 2 Ladestationen und 1 Ladekabel",
    status_on_website: "outofstock",
    wc_url:
      "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/heimwerker/akku-bohrschrauber/",
    wc_id: 3349,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/007.jpg",
  },
  {
    _id: "0008",
    item_name: "Nähmaschine",
    brand: "Medion",
    itype: "overlook MD 16600",
    category: "Haushalt",
    deposit: 55,
    parts: "1",
    manual: "in Schriftform vorhanden",
    package: "originalKarton",
    added: 1580342400000,
    properties: "Nähen, Schneidern, Versäubern (1300 Stiche pro Minute)/nur 3 Aufstecker",
    status_on_website: "instock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/haushalt/naehmaschine-2/",
    wc_id: 3350,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/008.jpg",
  },
  {
    _id: "0009",
    item_name: "Joghurt-Automat",
    brand: "gourmetmaxx",
    itype: "XJ -10101",
    category: "Küche",
    deposit: 15,
    parts: "8",
    manual: "",
    package: "",
    added: 1580342400000,
    properties: "7Gläser inkl. Deckel",
    status_on_website: "instock",
    wc_url: "https://www.buergerstiftung-karlsruhe.de/leihlokal/sortiment/kueche/einmachglaeser/",
    wc_id: 3351,
    image: "https://www.buergerstiftung-karlsruhe.de/wp-content/uploads/2020/01/009.jpg",
  },
  {
    _id: "0010",
    item_name: "nicht neu vergeben jetzt 217",
    brand: "",
    itype: "",
    category: "",
    deposit: 0,
    parts: "",
    manual: "",
    package: "",
    added: 0,
    properties: "",
    status_on_website: "deleted",
  },
];
