name: Test

on:
  push:
    branches: [integration_tests]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Test
        working-directory: Frontend
        run: npm ci && npm test

      - name: Install Chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Start CouchDB
        working-directory: CouchDb
        run: docker run -p 5984:5984 -p 6984:6984 -e COUCHDB_USER=user -e COUCHDB_PASSWORD=password -v "$(pwd)"/couchdb_config:/opt/couchdb/etc/local.d -v "$(pwd)"/couchdb_ssl:/opt/couchdb/ssl -d couchdb:3.1.1

      - name: Wait for CouchDB
        uses: MaximeGoyette/wait-for-it-action@master
        with:
          host: localhost
          port: 5984
          timeout: 60

      - name: Run integration tests
        working-directory: Frontend
        run: npm run integration_test
