name: Test

on:
  push:
    branches: [integration_tests]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Test
        working-directory: Frontend
        run: npm ci && npm test

      - name: Install Chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Start CouchDB
        run: docker-compose up -d

      - name: Wait for CouchDB
        run: wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x ./wait-for-it.sh && ./wait-for-it.sh -t 30 localhost:5984

      - name: Run integration tests
        working-directory: Frontend
        run: npm run integration_test
