name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Test
        working-directory: Frontend
        run: npm ci && npm test

      - name: Integration Test
        uses: cypress-io/github-action@v2
        with:
          working-directory: "./Frontend"
          command: npm run cy:run
          browser: chrome
        uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: cypress-screenshots
            path: cypress/screenshots
        uses: actions/upload-artifact@v1
          if: always()
          with:
            name: cypress-videos
            path: cypress/videos
