name: Test, Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        working-directory: Frontend
        env:
          COUCHDB_USER: "user"
          COUCHDB_HOST: "leihlokal.ddns.net:6984"
          COUCHDB_SSL: "true"
        run: |
          npm ci
          npm run build
      
      - name: Test
        working-directory: Frontend
        run: npm test
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: Frontend/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}