name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Test
        working-directory: Frontend
        run: npm ci && npm test

      - name: Run integration tests
        uses: Xotabu4/selenoid-github-action@v1
        with:
          working-directory: "./Frontend"
          command: npm run integration_test
