name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Test
        working-directory: Frontend
        run: npm ci && npm test

      - name: Start selenoid
        uses: ajinx/selenoid@v2
      - name: Run integration tests
        working-directory: Frontend
        run: npm run integration_test
